name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-14 ] # macos-14 is macOS 14 Arm64
        framework_version: [ 'net9.0', 'net48' ]
        exclude:
          - os: ubuntu-latest
            framework_version: 'net48'
          - os: macos-14
            framework_version: 'net48'
      fail-fast: false    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x      
      - name: Run Dev tests
        run: dotnet test tests/ShapeCrawler.DevTests/ShapeCrawler.DevTests.csproj -c Release -f ${{ matrix.framework_version }}
      - name: Run CI tests
        run: dotnet test tests/ShapeCrawler.CITests/ShapeCrawler.CITests.csproj -c Release -f ${{ matrix.framework_version }}